apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyloggerbackend-mongodb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keyloggerbackend-mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keyloggerbackend-mongodb
    spec:
      containers:
      - image: bitnami/mongodb:latest
        name: keyloggerbackend-mongodb
        ports:
        - containerPort: 27017
        env:
          - name: MONGODB_INITIAL_PRIMARY_HOST
            valueFrom:
              configMapKeyRef:
                key: MONGODB_INITIAL_PRIMARY_HOST
                name: keyloggerbackend-mongodb-env
          - name: MONGODB_DATABASE
            valueFrom:
              configMapKeyRef:
                key: KEYLOGGER_DATABASE_NAME
                name: keyloggerbackend-mongodb-env
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: MONGODB_ROOT_PASSWORD
                name: keyloggerbackend-mongodb-env
          - name: MONGODB_USERNAME
            valueFrom:
              configMapKeyRef:
                key: KEYLOGGER_DATABASE_PASSWORD
                name: keyloggerbackend-mongodb-env
          - name: MONGODB_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: KEYLOGGER_DATABASE_PASSWORD
                name: keyloggerbackend-mongodb-env
          - name: MONGO_PORT
            valueFrom:
              configMapKeyRef:
                key: KEYLOGGER_DATABASE_PORT
                name: keyloggerbackend-mongodb-env
      restartPolicy: Always
      serviceAccountName: ""
